[package]
name = "opengauss-derive-test"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[dev-dependencies]
trybuild = "1.0"

opengauss-types = { path = "../opengauss-types", features = ["derive"] }
postgres = { path = "../opengauss" }
