[workspace]
members = [
    "codegen",
    "opengauss",
    "opengauss-derive",
    "opengauss-derive-test",
    "opengauss-native-tls",
    "opengauss-openssl",
    "opengauss-protocol",
    "opengauss-types",
    "tokio-postgres",
]

[profile.release]
debug = 2
